### ISSUE TITLE
remove strip_tags call in postcomment.php

### ISSUE THREAD

**Issue by baskervald** [naomiEve/danger-u-#4]
strip_tags is, as far as I can tell, unnecessary in postcomment.php, considering htmlspecialchars replaces angle brackets with \&lt; and \&gt;

It breaks posts with any angle brackets in them. A left angle bracket will remove everything after it, and a pair will remove everything in-between them, with no indication of this to the user before they post.

**Comment by naomiEve** [comment]
changed in the src, will patch on the server tommorow
